# -*- coding: utf-8 -*-
"""
Constants for the services layer (business logic).
"""

# Severity level constants
SEVERITY_ERROR = "ERROR"
SEVERITY_WARNING = "WARNING"
SEVERITY_INFO = "INFO"

# Locale constants
LOCALE_RU = "ru"
LOCALE_UK = "uk"
LOCALE_BE = "be"
LOCALE_UNIVERSAL = "*"
LOCALE_EAST_SLAVIC = {LOCALE_RU, LOCALE_UK, LOCALE_BE}

# Historical year constants
REFORM_YEAR_1918 = 1918
DEFAULT_DB_MEDIAN_YEAR = 1920

# Confidence score thresholds
CONFIDENCE_THRESHOLD_MINIMUM = 0.60
CONFIDENCE_SCORE_CYRILLIC = 0.50
CONFIDENCE_SCORE_SLAVIC_SURNAME = 0.20
CONFIDENCE_SCORE_SIBLING = 0.30
CONFIDENCE_SCORE_FALLBACK = 0.20

# Reference source constants
REF_SOURCE_LATEST_EVENT = "LATEST_EVENT"
REF_SOURCE_GRAPH_BFS = "GRAPH_BFS"
REF_SOURCE_DB_MEDIAN_FALLBACK = "DB_MEDIAN"
